name: halodrops_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.10
  - sphinx
  - ca-certificates
  - openssl
  - myst-parser
  - certifi
  - sphinx-autobuild
  - numpy
  - nbsphinx
  - pip>=20.1
  - xarray
  - netcdf4
  - ipython
  - pre-commit
  - metpy
  - pip:
    - sphinx-autodoc2
    - sphinx-book-theme
    - sphinx-last-updated-by-git
    - -e .
